services:
  vlei-verifier-router:
    network_mode: host
    build:
      context: .
      dockerfile: ./images/vlei-verifier-router.dockerfile
    image: gleif/vlei-verifier-router:latest
    environment:
      REDIS_HOST: localhost
      REDIS_PORT: 6379
    ports:
      - 7676:7676
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:7676/health
      interval: 2s
      timeout: 3s
      retries: 5
      start_period: 2s

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

volumes:
  redis_data:


